
import { ReduxProvider } from "@/redux/ReduxProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import Whatsapp from "./components/whatsapp/Whatsapp";
import UserInitializer from "./components/userInit/UserInitializer";
import AppWrapper from "./components/appWrapper/AppWrapper";


const inter = Inter({subsets:["latin"], weight:["100","200","300","400","500","600","700","800","900"]})
export const metadata = {
  title: "Lulu Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ReduxProvider >
          <AppWrapper>
            {children}
          </AppWrapper>
        </ReduxProvider>
        <Whatsapp />
      </body>
    </html>
  );
}
