
import { ReduxProvider } from "@/redux/ReduxProvider";
import Footer from "./components/footer/Footer";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Whatsapp from "./components/whatsapp/Whatsapp";


const inter = Inter({subsets:["latin"]})
export const metadata = {
  title: "Lulu Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ReduxProvider >
        <Navbar />
        {children}
        <Footer />
        </ReduxProvider>
        <Whatsapp />
      </body>
    </html>
  );
}
